#!/bin/bash

# Check if specific files are provided as arguments
if [ $# -gt 1 ]; then
  # Add specific files to the staging area
  git add "${@:1:$#-1}"
else
  # Add all changes to the staging area
  git add .
fi

# Commit the changes with the provided message
commit_message="${@: -1}"
git commit -m "$commit_message"

# Push the commits to the remote repository
git push

git status .

